[IPCT1-654] - Log of changes
impactMarket/backend pull request #216
Opened 2022-03-07 14:09 UTC by dev-jotape

This PR fixes [IPCT1-654] at https://impactmarket.atlassian.net/browse/IPCT1-654

## Changes
register a log of changes, when:
- when a community is edited
- when a user edits a profile

## Tests
new tests added in user.test file

2022-03-08 12:00 UTC, obernardovieira requested changes

2022-03-08 12:00 UTC, obernardovieira commented on packages/core/src/services/app/user.ts
> +            user.address,
you could use updated[0].id I think. THis goes together with my comment on "why not accepting just id?"

2022-03-08 12:00 UTC, obernardovieira commented on packages/core/src/services/app/appLog.ts
> +        user: string | number,
why not accept just id?

2022-03-10 14:28 UTC, dev-jotape commented
@obernardovieira I made a refactor, could you validate again, please?

2022-03-10 20:04 UTC, obernardovieira requested changes

2022-03-16 00:32 UTC, dev-jotape commented on packages/core/src/services/app/user/log.ts
> +        });
right! I changed a little the function

2022-03-21 12:16 UTC, obernardovieira approved these changes

2022-03-21 12:16 UTC, merged