review list beneficiaries cache
impactMarket/backend pull request #538
Opened 2023-03-10 22:10 UTC by dev-jotape

This PR fixes #529 

## Changes
Clean cache when a beneficiary is added or removed

## Tests

2023-03-15 11:01 UTC, obernardovieira requested changes
Just some minor cleanups 😉

2023-03-21 17:47 UTC, dev-jotape commented on packages/core/src/subscriber/chainSubscribers.ts
> +        );
ok, removed.

2023-03-21 17:48 UTC, dev-jotape commented on packages/core/src/subscriber/chainSubscribers.ts
> +                ethers.utils.id('BeneficiaryRemoved(address,address)'),
ok, removed

2023-03-21 18:28 UTC, obernardovieira approved these changes
🥳

2023-03-22 14:40 UTC, merged