add microcredit form
impactMarket/backend pull request #666
Opened 2023-06-07 16:03 UTC by dev-jotape

This PR fixes #564 

## Changes
Create `microcredit-form` table with a JSONB column to save the form.
When the user wants to submit the form, should send a flag called `submit` on the request.

## Tests

2023-06-09 09:51 UTC, obernardovieira requested changes

2023-06-13 20:44 UTC, dev-jotape commented on packages/api/src/controllers/v2/protocol/index.ts
> +import { RequestWithUser } from 'middlewares/core';
fixed

2023-06-13 20:45 UTC, dev-jotape commented on packages/api/src/routes/v2/protocol/microcredit.ts
> +    )
Yes, totally sense
I moved from /protocol to /microcredit

2023-06-15 10:43 UTC, obernardovieira commented
just rebased and fixed conflicts

2023-06-15 10:44 UTC, obernardovieira approved these changes

2023-06-15 11:47 UTC, merged