add microcredit notes
impactMarket/backend pull request #742
Opened 2023-07-11 21:06 UTC by dev-jotape

This PR fixes #674 

## Changes
Add a field `notes` on the `microcredit-form` table, and a new endpoint to save these notes when a microcredit application is in-review.

## Tests

2023-07-13 11:13 UTC, obernardovieira requested changes
Notes should be a separate table
<img width="797" alt="image" src="https://github.com/impactMarket/backend/assets/19441097/796bffdb-d2f2-46b0-b699-4a0a65f03886">

2023-07-14 15:48 UTC, dev-jotape commented
@obernardovieira can you validate again, please?

2023-07-17 11:48 UTC, obernardovieira requested changes

2023-07-17 11:48 UTC, obernardovieira commented on packages/core/src/database/models/associations/microcredit.ts
> +    });
You can include this association on the user associations file

2023-07-19 14:43 UTC, obernardovieira approved these changes

2023-07-19 14:43 UTC, merged