[feature] send push notification when user receives a transfer
impactMarket/backend pull request #832
Opened 2023-08-23 17:30 UTC by dev-jotape

This PR fixes #744 

## Changes
Send push notification when a user receives a transfer from the following assets: cUSD, cEUR, cREAL, CELO, and PACT.

## Tests

2023-08-24 17:46 UTC, obernardovieira requested changes

2023-08-29 20:50 UTC, dev-jotape commented on packages/core/src/interfaces/app/appNotification.ts
> +    TRANSACTION_RECEIVED = 'transactions/'
ok, removed

2023-08-29 20:51 UTC, dev-jotape commented on packages/core/src/subscriber/chainSubscribers.ts
> +            sendNotification([user], NotificationType.TRANSACTION_RECEIVED, true, true, {
done, please can you review it again?

2023-08-31 09:37 UTC, obernardovieira approved these changes

2023-08-31 09:37 UTC, obernardovieira commented on packages/core/src/subscriber/chainSubscribers.ts
> +                asset
It's just missing the transaction hash on the path, so we can show the bottom sheet straight away on the wallet. I think the parameter is correct https://docs.ethers.org/v5/api/providers/types/#providers-Log

```suggestion
                asset,
                path: log.transactionHash
```

2023-08-31 13:56 UTC, merged